name: Получить файл активации Unity

on:
  workflow_dispatch: {}

jobs:
  activation:
    name: Request manual activation file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: game-ci/unity-activate@v3.0.0-beta.1
      - uses: actions/upload-artifact@v4
        with:
          name: Manual Activation File
          path: activation